name: Build, test & deploy to prod

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: serverless deploy
        uses: serverless/github-action@v2
        with:
          args: deploy --conceal --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACKBOT_SERVICE_URL: ${{ secrets.SLACKBOT_SERVICE_URL }}
          SLACKBOT_SERVICE_API_KEY: ${{ secrets.SLACKBOT_SERVICE_API_KEY }}
